{% set name = "pyfolio-reloaded" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2b522ff514579b2760ad9a95d02cadd02078621c5da8c34a091a44de554a71d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - ipython >=3.2.3
    - matplotlib-base >=1.4.0
    - numpy >=1.11.1
    - pandas >=0.18.1
    - pytz >=2014.10
    - scipy >=0.14.0
    - scikit-learn >=0.16.1
    - seaborn >=0.7.1
    - empyrical-reloaded >=0.5.8

test:
  imports:
    - pyfolio
  source_files:
    - tests
  commands:
    - pytest --ignore tests/test_timeseries.py tests/
  requires:
    - coverage >=4.0.3
    - coveralls ==3.0.1
    - pytest >=6.2
    - pytest-xdist >=2.5.0
    - pytest-cov >=2.12
    - parameterized >=0.6.1
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pyfolio-reloaded/
  summary: Performance and risk analysis of financial portfolios with Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefan-jansen
